# Use official Node.js image
FROM node:20

# Set working directory
WORKDIR /ostad-server

# Copy backend code
COPY OstadServer/ .

# Install dependencies
RUN npm install

# Expose backend port
EXPOSE 5050

# Run the server
CMD ["node", "server.js"]
