version: "3.8"
 
services:
  backend:
	build:
  	context: .
  	dockerfile: Dockerfile-server
	ports:
  	- "5050:5050"
	depends_on:
  	- mongo
	environment:
  	- MONGO_URL=mongodb://ostad:ostad@mongo:27017/ostad_db
 
  frontend:
	build:
  	context: .
  	dockerfile: Dockerfile-UI
	ports:
  	- "5173:5173"
	depends_on:
  	- backend
 
  mongo:
	image: mongo:latest
	environment:
      MONGO_INITDB_ROOT_USERNAME: ostad
      MONGO_INITDB_ROOT_PASSWORD: ostad
	ports:
  	- "27017:27017"
 
  mongo-express:
	image: mongo-express:latest
	ports:
  	- "8081:8081"
	environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ostad
      ME_CONFIG_MONGODB_ADMINPASSWORD: ostad
      ME_CONFIG_MONGODB_SERVER: mongo
	depends_on:
  	- mongo

