# Use official Node.js image
FROM node:20

# Set working directory
WORKDIR /ostadui

# Copy package.json and package-lock.json
COPY OstadUI/package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the frontend code
COPY OstadUI/ .

# Expose frontend dev server port
EXPOSE 5173

# Run the dev server
CMD ["npm", "run", "dev"]

